# Generated by Django 4.2.29 on 2026-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_lower',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Название (нижний регистр)'),
        ),
    ]
