# Generated by Django 4.2.29 on 2026-05-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_name_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время доставки'),
        ),
    ]
