# Generated by Django 4.2.29 on 2026-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default='Италия', max_length=100, verbose_name='Страна производства'),
        ),
    ]
