# Generated by Django 4.2.29 on 2026-04-01 11:18

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='metal',
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_upload_path, verbose_name='Дополнительное фото 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_upload_path, verbose_name='Дополнительное фото 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_upload_path, verbose_name='Дополнительное фото 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_upload_path, verbose_name='Дополнительное фото 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='product',
            name='silver_type',
            field=models.CharField(choices=[('sterling', 'Стерлинговое серебро (925)'), ('fine', 'Чистое серебро (999)'), ('argentium', 'Аргентиум серебро'), ('mexican', 'Мексиканское серебро'), ('oxidized', 'Оксидированное серебро'), ('rhodium_plated', 'Серебро с родиевым покрытием'), ('black', 'Черненое серебро'), ('matte', 'Матовое серебро')], default='sterling', max_length=30, verbose_name='Тип серебра'),
        ),
        migrations.AddField(
            model_name='product',
            name='stone_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общий вес всех камней в каратах', max_digits=8, null=True, verbose_name='Вес камней (карат)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fineness',
            field=models.CharField(choices=[('800', '800 проба'), ('830', '830 проба'), ('875', '875 проба'), ('900', '900 проба'), ('916', '916 проба'), ('925', '925 проба'), ('960', '960 проба'), ('999', '999 проба')], default='925', max_length=4, verbose_name='Проба серебра'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное фото товара', null=True, upload_to=shop.models.product_image_upload_path, verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Например: 16.5, 17, 18, S, M, L', max_length=50, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stone_type',
            field=models.CharField(blank=True, choices=[('diamond', 'Бриллиант'), ('ruby', 'Рубин'), ('sapphire', 'Сапфир'), ('emerald', 'Изумруд'), ('topaz', 'Топаз'), ('amethyst', 'Аметист'), ('garnet', 'Гранат'), ('peridot', 'Перидот'), ('citrine', 'Цитрин'), ('aquamarine', 'Аквамарин'), ('tourmaline', 'Турмалин'), ('opal', 'Опал'), ('pearl', 'Жемчуг'), ('cubic_zirconia', 'Фианит'), ('moonstone', 'Лунный камень'), ('none', 'Нет камней')], max_length=30, null=True, verbose_name='Тип камня'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stones',
            field=models.BooleanField(default=False, verbose_name='Наличие драгоценных камней'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес изделия (г)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='shop_produc_is_acti_2257ae_idx'),
        ),
    ]
