# Generated by Django 4.2.29 on 2026-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_collection_alter_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время генерации кода'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('received', 'Получен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
