# Generated by Django 4.2.29 on 2026-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_earned',
            field=models.IntegerField(default=0, verbose_name='Начислено бонусов'),
        ),
    ]
