# Generated by Django 4.2.29 on 2026-05-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_code_generated_at_order_pickup_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_time',
        ),
    ]
