# Generated by Django 4.2.29 on 2026-05-15 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
    ]
