# Generated by Django 4.2.29 on 2026-05-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_delivery_date_order_delivery_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
